/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SliderZooming.java
 *
 * Created on Nov 22, 2008, 3:17:24 PM
 */
package hilbert;

import javax.swing.JSlider;

/**
 *
 * @author Georgios
 */
public class SliderSharpness extends javax.swing.JPanel {

    /** Creates new form SliderZooming */
    public SliderSharpness() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scaleSlider_Ratio = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(200, 20));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scaleSlider_Ratio.setBackground(new java.awt.Color(255, 255, 255));
        scaleSlider_Ratio.setMajorTickSpacing(1);
        scaleSlider_Ratio.setMaximum(255);
        scaleSlider_Ratio.setMinimum(1);
        scaleSlider_Ratio.setMinorTickSpacing(1);
        scaleSlider_Ratio.setSnapToTicks(true);
        scaleSlider_Ratio.setValue(1);
        scaleSlider_Ratio.setOpaque(true);
        scaleSlider_Ratio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                scaleSlider_RatioStateChanged(evt);
            }
        });
        add(scaleSlider_Ratio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sharpness");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void scaleSlider_RatioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_scaleSlider_RatioStateChanged
        JSlider src = (JSlider) evt.getSource();
        if (!src.getValueIsAdjusting()) {
            // Meander.jMenuItem10.setScale(src);

            Variables.sharpness = src.getValue();
            int factor = (259 * ((int)Variables.contrast  + 255)) / (255 * (259 - (int)Variables.contrast ));
            
          /*  for (int i = 0; i < Variables.pixels.size(); i++) {
               Pixel pix = Variables.pixels.get(i);
               ColorHilbert colour = new ColorHilbert(pix.getColor_hilbert_ratio());
               ColorHilbert new_colour = new ColorHilbert();
               new_colour.R=(factor * (colour.R   - 128) + 128);
               new_colour.G=(factor * (colour.G   - 128) + 128);
               new_colour.B=(factor * (colour.B   - 128) + 128);
               pix.setColor_hilbert_ratio(new_colour);    
            }
            Hilbert.changeHilbert();*/
 
            System.out.println("Variables.sharpness:"+Variables.sharpness);
            

        }
        

    }//GEN-LAST:event_scaleSlider_RatioStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JSlider scaleSlider_Ratio;
    // End of variables declaration//GEN-END:variables
}
