/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hilbert;

import controlP5.DropdownList;
import controlP5.Textfield;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Hashtable;
import javax.swing.JPopupMenu;
import processing.core.PGraphics;
import processing.core.PImage;

/**
 *
 * @author gpavlopo
 */
public class Variables {

    public static ColorHilbert generic_color = new ColorHilbert(255, 255, 255);
    public static String codebase;
    public static String file_with_reads = null;
    public static String file_with_variations = null;
    public static String file_with_pair_ends = null;
    public static String chromosome = "";
    public static int min_chromosome_position = 999999999;
    public static int max_chromosome_position = -1;
    public static int min_chromosome_position_of_the_zoomed_area = 999999999;
    public static int max_chromosome_position_of_the_zoomed_area = -1;
    public static double min_read_sample1 = 999999999;
    public static double max_read_sample1 = -999999999;
    public static double min_read_sample2 = 999999999;
    public static double max_read_sample2 = -999999999;
    public static double min_read_sample3 = 999999999;
    public static double max_read_sample3 = -999999999;
    public static double min_read_sample4 = 999999999;
    public static double max_read_sample4 = -999999999;
    public static double min_read_reference = 999999999;
    public static double max_read_reference = -999999999;
    public static double max_read_ratio1 = -999999999;
    public static double min_read_ratio1 = 999999999;
    public static double max_read_ratio2 = -999999999;
    public static double min_read_ratio2 = 999999999;
    public static double max_read_ratio3 = -999999999;
    public static double min_read_ratio3 = 999999999;
    public static double max_read_ratio4 = -999999999;
    public static double min_read_ratio4 = 999999999;
    public static double average_read_sample1 = 0;
    public static double average_read_sample2 = 0;
    public static double average_read_sample3 = 0;
    public static double average_read_sample4 = 0;
    public static double average_read_reference = 0;
    public static double average_ratio1 = 0;
    public static double average_ratio2 = 0;
    public static double average_ratio3 = 0;
    public static double average_ratio4 = 0;
    public static ArrayList<Coordinate> highlight_zoom_point_list = new ArrayList();
    public static ArrayList<Pixel> highlight_zoom_pixel_list = new ArrayList();
    public static ColorHilbert cross = new ColorHilbert("red");
    public static ColorHilbert up_regulated = new ColorHilbert("blue");
    public static ColorHilbert down_regulated = new ColorHilbert("red");
    public static double contrast = 1;
    public static double contrast_memory = 2; //should be different that contrast for initilization
    public static double sharpness = 1;
    public static double max_value_color_for_reference = 300;
    public static double max_value_color_for_sample = 300;
    public static double max_value_color_for_ratio = 3f;
    public static boolean ratio_enabled = false;
    public static boolean variation_enabled = false;
    public static boolean sample_enabled = false;
    public static boolean ratio_values_exist = false;
    public static boolean reference_values_exist = false;
    public static boolean sample_values_exist = false;
    public static boolean deletions_enabled = true;
    public static boolean insertions_enabled = true;
    public static boolean inversions_enabled = true;
    public static boolean translocations_enabled = true;
    public static boolean duplications_enabled = true;
    public static boolean enable_pair_end_lines = true;
    public static boolean initial_calculations_made = false;
    public static boolean reference_enabled = false;
    public static boolean pause_everything = false;
    public static boolean min_max_position_is_set = false;
    public static boolean pair_ends_enabled = false;
    public static int something_changed = 0;
    public static boolean zooming_window_enabled = false;
    public static NumberFormat formatter = new DecimalFormat("#,###,###");
    //public static String chromosome_selected = null;
    //public static String chromosome = null;
    public static String meander_file = null;
    public static int upper_threshold = 0;
    public static int lower_threshold = 0;
    public static int dimension = 512;
    public static Zooming_Info zooming_file_to_be_loaded = null;
    public static int fold_level = 9;
    public static boolean show_welcome_screen = false;
    public static Hashtable<Integer, Integer> give_zoom_get_size = new Hashtable();
    public static int zoom_tmp = 1;
    public static int zoom = 1;
    public static PGraphics pg1;
    public static PGraphics pg1_copy1;
    public static PGraphics pg1_copy2;
    public static PImage pi1;
    public static PImage pi1_enhanced;
    public static PImage pi1_copy1;
    public static PImage pi1_copy2;
    public static PGraphics pg2;
    public static PGraphics pg2_copy1;
    public static PGraphics pg2_copy2;
    public static PImage pi2;
    public static PImage pi2_enhanced;
    public static PImage pi2_copy1;
    public static PImage pi2_copy2;
    public static PGraphics pg3;
    public static PGraphics pg3_copy1;
    public static PGraphics pg3_copy2;
    public static PImage pi3;
    public static PImage pi3_enhanced;
    public static PImage pi3_copy1;
    public static PImage pi3_copy2;
    public static PGraphics pg4;
    public static PGraphics pg4_copy1;
    public static PGraphics pg4_copy2;
    public static PImage pi4;
    public static PImage pi4_enhanced;
    public static PImage pi4_copy1;
    public static PImage pi4_copy2;

    public static int mouse_x;
    public static int mouse_y;
    public static JPopupMenu menu;
    public static boolean finished_hilbert_drawing_for_first_time = false;
    public static boolean finished_pair_end_drawing_for_first_time = false;
    public static boolean pair_ends_initial_loaded = false;
    public static boolean pair_ends_selected = false;
    public static ArrayList<Pixel> pixels_initial = new ArrayList();
    public static ArrayList<Pixel> pixels = new ArrayList();
    public static Hashtable<String, Pixel> give_coordinate_get_pixel_initial = new Hashtable();
    public static Hashtable<String, Pixel> give_coordinate_get_pixel = new Hashtable();
    public static ArrayList<Zooming_Info> zooming_file_list = new ArrayList();
    public static Coordinate highlight_hilbert_point = new Coordinate(128, 128);
    public static Coordinate highlight_hilbert_point_zoomed = new Coordinate(256, 256);
    public static int highlight_hilbert_chromosome_point_zoomed;
    public static int zooming_grid_index_x = 0;//variables to choose zooming file
    public static int zooming_grid_index_y = 0;
    public static ArrayList<Variation> variation_list = new ArrayList();
    public static ArrayList<Integer> sample_histogram1 = new ArrayList();
    public static ArrayList<Integer> sample_histogram2 = new ArrayList();
    public static ArrayList<Integer> sample_histogram3 = new ArrayList();
    public static ArrayList<Integer> sample_histogram4 = new ArrayList();
    public static ArrayList<Integer> PE_histogram = new ArrayList();
    public static int PE_histogram_max_value = -1;
    public static int PE_max_value = -1;
    public static int sample_histogram_max_value1 = -1;
    public static int reference_histogram_max_value1 = -1;
    public static int ratio_histogram_max_value1 = -1;
    public static int sample_histogram_max_value2 = -1;
    public static int reference_histogram_max_value2 = -1;
    public static int ratio_histogram_max_value2 = -1;
    public static int sample_histogram_max_value3 = -1;
    public static int reference_histogram_max_value3 = -1;
    public static int ratio_histogram_max_value3 = -1;
    public static int sample_histogram_max_value4 = -1;
    public static int reference_histogram_max_value4 = -1;
    public static int ratio_histogram_max_value4 = -1;
    public static Textfield position_textfield;
    public static DropdownList check_sample_ref_ratio;
    public static DropdownList check_variations;
    public static ArrayList<Integer> reference_histogram1 = new ArrayList();
    public static ArrayList<Integer> reference_histogram2 = new ArrayList();
    public static ArrayList<Integer> reference_histogram3 = new ArrayList();
    public static ArrayList<Integer> reference_histogram4 = new ArrayList();
    public static ArrayList<Integer> ratio_histogram1 = new ArrayList();
    public static ArrayList<Integer> ratio_histogram2 = new ArrayList();
    public static ArrayList<Integer> ratio_histogram3 = new ArrayList();
    public static ArrayList<Integer> ratio_histogram4 = new ArrayList();
    public static ArrayList<Coordinate> tmp_coor_pair_end = new ArrayList();
    public static ArrayList<Coordinate> pe_marking_for_first_zoom_level = new ArrayList();
    public static ArrayList<Coordinate> overlaid_hilbert = new ArrayList();
    public static ArrayList<Pixel> pair_ends_for_zoom_level = new ArrayList();
    public static ArrayList<DoubleEvidence> circles = new ArrayList();
    public static float upper_ratio_threshold = 5;
    public static float lower_ratio_threshold = -5;
    // public static Hashtable<Interval, Pixel> searchTree_pair_ends = null;
    public static IntervalST<Pixel> searchTree_pair_ends = new IntervalST();
    // public static IntervalST<Pixel> searchTree_pair_ends_initial = null;
    public static IntervalST<Pixel> searchTree_Coordinates = null;
    public static int pair_end_minimum_distance_threshold = 100;
    public static int pair_end_maximum_distance_threshold = 100000000;
    public static int pair_end_count_of_cluster = 1;
    public static boolean select_whole_area = false;
    public static ArrayList<PairEnd> pair_end_list_to_highlight = new ArrayList();
    public static ArrayList<PairEnd> pair_end_list_to_highlight_initial = new ArrayList();
    public static ArrayList<Pixel> pair_end_list_to_highlight_initial_zooming_panel = new ArrayList();
    public static ArrayList<PairEnd> pair_end_list = null;
    public static ArrayList<String> chromosome_list = new ArrayList();
    public static String organism = "human";
    public static boolean organisms_load_allowance = false;
    public static boolean organisms_loaded_once = false;
    public static ArrayList<Integer> get_human_Chr_lengths = new ArrayList();
    public static ArrayList<String> get_human_Chr_names = new ArrayList();
    public static ArrayList<Integer> get_arabidopsis_Chr_lengths = new ArrayList();
    public static ArrayList<String> get_arabidopsis_Chr_names = new ArrayList();
    public static ArrayList<Integer> get_rat_Chr_lengths = new ArrayList();
    public static ArrayList<String> get_rat_Chr_names = new ArrayList();
    public static ArrayList<Integer> get_drosophila_Chr_lengths = new ArrayList();
    public static ArrayList<String> get_drosophila_Chr_names = new ArrayList();
    public static ArrayList<Integer> get_chimp_Chr_lengths = new ArrayList();
    public static ArrayList<String> get_chimp_Chr_names = new ArrayList();
    public static ArrayList<Integer> get_mouse_Chr_lengths = new ArrayList();
    public static ArrayList<String> get_mouse_Chr_names = new ArrayList();
    public static ArrayList<Integer> get_zebrafish_Chr_lengths = new ArrayList();
    public static ArrayList<String> get_zebrafish_Chr_names = new ArrayList();
    public static ArrayList<Integer> chromosome_ends = new ArrayList();
    public static ArrayList<String> names = new ArrayList();
    public static ArrayList<Integer> lengths = new ArrayList();
    public static Hashtable<Integer, Coordinate> give_position_get_Coordinate_for_Chromosomes = new Hashtable();
    public static int translation = 20;
    public static int pair_ends_counter = 0;
    public static int panel = 1;
    public static boolean interchromosomal = true;
    public static boolean panel1_has_information = true;
    public static boolean panel2_has_information = false;
    public static boolean panel3_has_information = false;
    public static boolean panel4_has_information = false;
    public static String panel1_label = "sample 1";
    public static String panel2_label = "sample 2";
    public static String panel3_label = "sample 3";
    public static String panel4_label = "sample 4";
    public static int visualization_mode_PE_RD = 3; //1=just RD 2=just PE 3=RD+PE
}
